# Generated by Django 3.2 on 2021-04-25 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_type', models.CharField(choices=[('electronic', 'Electronics'), ('entertainment', 'Movies, Music & Games'), ('clothing', 'Clothing, Shoes & Jewelry'), ('book', 'Books'), ('electronic', 'Electronics'), ('other', 'Other')], default='other', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
